### ISSUE TITLE
Bug in napi folder

### ISSUE THREAD

**Issue by Globik** [nodejs/abi-stable-node-addon-examples#14]
There in .js file must be simply require without ('addon'). Segmentation fault.

**Comment by mhdawson** [comment]
Can you provide a bit more context info as to how to reproduce ?

**Comment by Globik** [comment]
Oh, I figured out why. I was wrong with require routine. Not a bug. I was my mistake. Please close this issue.

**Comment by mhdawson** [comment]
Closing as requested.
