### ISSUE TITLE
Provide examples (NAPI) creating multiple properties

### ISSUE THREAD

**Issue by khvalov** [nodejs/abi-stable-node-addon-examples#18]
Curent examples cover cases only with 1 properties get created inside Init. 
Is any chance to give examples how to create multiple properties? 

next approach is incorrect - it's overwrite exports 
```

napi_value Init(napi_env env, napi_value exports) {
  napi_status status;
  napi_value fn;
  
  read_dht_data();

  status = napi_create_function(env, NULL, 0, myGetTemp, NULL, &fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to wrap native function");
  }

  status = napi_set_named_property(env, exports, "getTemp", fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to populate exports");
  }

status = napi_create_function(env, NULL, 0, myGetTemp2, NULL, &fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to wrap native function");
  }

  status = napi_set_named_property(env, exports, "getTemp2", fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to populate exports");
  }

  return exports;
}
```

**Comment by khvalov** [comment]
@mhdawson , thanks for reply. 
_>napi_set_named_property with "getTemp2" that removes the "getTemp" value set in the first call to napi_set_named_property?_
Correct

So my initial question is - could you please expose your sample with assigning 2 named properties

**Comment by mhdawson** [comment]
if it is removing the getTemp2 when getTemp is set then there is a bug that will need to be investigated.

**Comment by gniezen** [comment]
Is it maybe because you're using the variable `fn` for both functions? Does it work if you replace the first `fn` with `fn1` and the second `fn` with `fn2`?

**Comment by andrew-cc-chen** [comment]
@khvalov I was unable to recreate the error you encountered using the following code. The export contained both functions, instead of replacing the first function with the second like you mentioned.

```
napi_value Method(napi_env env, napi_callback_info args) {
  napi_value greeting;
  napi_status status;

  status = napi_create_string_utf8(env, "hello", NAPI_AUTO_LENGTH, &greeting);
  if (status != napi_ok) return nullptr;
  return greeting;
}

napi_value Method2(napi_env env, napi_callback_info args) {
  napi_value greeting;
  napi_status status;

  status = napi_create_string_utf8(env, "hello2", NAPI_AUTO_LENGTH, &greeting);
  if (status != napi_ok) return nullptr;
  return greeting;
}

napi_value Init(napi_env env, napi_value exports) {
  napi_status status;
  napi_value fn;

    status = napi_create_function(env, NULL, 0, Method, NULL, &fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to wrap native function");
  }

  status = napi_set_named_property(env, exports, "hello", fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to populate exports");
  }

  status = napi_create_function(env, NULL, 0, Method2, NULL, &fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to wrap native function");
  }

  status = napi_set_named_property(env, exports, "hello2", fn);
  if (status != napi_ok) {
    napi_throw_error(env, NULL, "Unable to populate exports");
  }

  return exports;
}

NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
```

[https://github.com/nodejs/node/tree/master/test/addons-napi/3_callbacks](url) provides another example of exporting two functions in a similar implementation, and it works correctly.

**Comment by xthdraft** [comment]
Andrew Chen's example works fine for me after adding the required header #include <node_api.h> and changing nullptr to NULL.

After building with node-gyp configure build, I used an extra build instruction for my version of electron:
node-gyp rebuild --target=3.0.6 --arch=x64 --dist-url=https://atom.io/download/electron

This code could well be decorated with comment lines and put in the docs, as it is a very useful example.

**Comment by mhdawson** [comment]
@khvalov we don't seem to be able to recreate the problem.  Unless you think otherwise I think this can be close

**Comment by mhdawson** [comment]
Going to close @khvalov if you still see the issue please open an issue in  https://github.com/nodejs/node-addon-examples where future work on the examples is being done.
